# Generated by Django 3.2.9 on 2021-12-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0005_auto_20211213_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Accept'), ('S', 'Sent')], max_length=50),
        ),
    ]
