# Generated by Django 3.2.9 on 2021-12-19 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0011_alter_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
    ]
